# Generated by Django 5.1.7 on 2025-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(help_text='Describe the item (e.g., color, brand, size, unique features)')),
                ('location_found', models.CharField(help_text='Where did you find the item?', max_length=255)),
                ('date_found', models.DateField(help_text='Date when the item was found')),
                ('upload_photo', models.ImageField(blank=True, help_text='Optional photo of the item', null=True, upload_to='found_items/')),
                ('contact_info', models.CharField(blank=True, help_text='Contact email or phone number', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('location_lost', models.CharField(max_length=255)),
                ('date_lost', models.DateField()),
                ('contact_info', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
