# Generated by Django 5.1.7 on 2025-03-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostFound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='upload_photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the item', null=True, upload_to='lost_items/'),
        ),
    ]
